### ISSUE TITLE
Lang crashing

### ISSUE THREAD

**Issue by HostingItAll** [williamtdr/Steadfast2#3]
+
+-Fatal error: Call to undefined method pocketmine\Server::getLanguage() in /home/452/src/pocketmine/Player.php on line 2359

19:57:26 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump

PocketMine-Steadfast Crash Dump Sun Jun 21 19:57:26 EDT 2015

Error: Call to undefined method pocketmine\Server::getLanguage()
File: /src/pocketmine/Player
Line: 2359
Type: E_ERROR

Code:
[2350] 								break;
[2351] 							}
[2352] 							if(substr($ev->getMessage(), 0, 1) === "/"){ //Command
[2353] 								Timings::$playerCommandTimer->startTiming();
[2354] 								$this->server->dispatchCommand($ev->getPlayer(), substr($ev->getMessage(), 1));
[2355] 								Timings::$playerCommandTimer->stopTiming();
[2356] 							}else{
[2357] 								$this->server->getPluginManager()->callEvent($ev = new PlayerChatEvent($this, $ev->getMessage()));
[2358] 								if(!$ev->isCancelled()){
[2359] 									$this->server->broadcastMessage($this->getServer()->getLanguage()->translateString($ev->getFormat(), [$ev->getPlayer()->getDisplayName(), $ev->getMessage()]), $ev->getRecipients());
[2360] 								}
[2361] 							}
[2362] 						}
[2363] 					}
[2364] 				}
[2365] 				break;
[2366] 			case ProtocolInfo::CONTAINER_CLOSE_PACKET:
[2367] 				if($this->spawned === \false or $packet->windowid === 0){
[2368] 					break;
[2369] 				}

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5 #0 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux bravo.hostingitall.com 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
xyz 1.0.1 by unerds for API(s) 1.0.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
AlwaysSpawn 2.2.1 by Philip Shilling for API(s) 1.12.0
RealTime 2.1 by Guillaume351 for API(s) 1.0.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
iProtector 3.1a by LDX for API(s) 1.9.0
PurePerms 1.1.2 by 64FF00 for API(s) 1.12.0
SAM 1.5.2 by Humerus,HostingItAll for API(s) 1.9.0
PureChat 1.2.6 by 64FF00 for API(s) 1.11.0
pvpoff 1 by  for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNq1WQtz27gR/iuokpnGHVES9bLFjDL1OM5dWjtWLaXuTHiTgUhI4pmvI0DLSib/vd8CIEXZTpPL
XZ2HiQWwu9++sCA/t1SUiJbnDgfDycDtDcftliiKrGh5n1tql2Oqdf7x/Pr66rrVbiVCSr4m2hmP
Y6YyVqahWEWpCFki1CYLWZ4Ft0IlIPn+XBR3ovC8tVAXPF2X2PriCGxWUUw8urIIuvv13VnMd6LA
fIxRy+sPRpMv7VYel+sobXkrHkvRbgVZKEg3zPbAw1eHf5aF4LcvwQPz7qP5L2ai/2giWr2Q5VKq
4sVzcee8gsKXBuqLozbrtZl7xKbTKfNbXb919Jl1u2dZkvA0NPwGTyiyiIBpLT3vea5h2Q0gi8J5
JRUv7JIXR1bd4RNcnqtNJLFcG9J5FUYy5yrYWGa1ssZypOvXUbhHlaDRD6ib5Q+0HT82roCDPpvZ
429j0WqTay95ChWhvfMqQFSd34lUEQA2ZanYMoPtbMOVnSE2bfYIYQ3v5AnZ8O9f9I5InvE0EHEs
Qmyx2k6e2PFI32WR8TDgspZo56GDiXMCcBDpzitV8FTGXIm5Ksh4ldJvsiLhirzy4aEL9eA1/Izx
O55o1z3C+kuDeC2CKI9gGfmiMsH4qcwwsT/+WlKMHyaFJR/GtiU2Q9WSmkHVSMLxPk5gO8FmRaay
IIvfpqvM886u3i1O3747v/54dnE1P/84Oz375/nCMzubMQT/Ve7I+ZbKjU5HXxcFlhXsec6pjjiv
tlEaZtvILOhZD48PY6Kp3+QACuoNfBagwnxoPeuxF0feEwUNcVpwuXldJjnK2S/t1lqkouAxlSVM
yyhDuWq5nREkLMsoDlteD3XMIkdhO263eB7pNW6/08OydaQw7H3nDzYU/DaOlrSnc6w5lCmnOt66
iNLyni0Lfpd1NplUCLtIIa06QZawfmfcGfSdUW/YOem4HRGPO/cn44/jIXvmsvnljN3Asv/gKeuf
sL7rua43GLP3izPW77kjZpZCVr7JIWkEZn2MPgnUQa9FvHtm8mMmK01A0INYD+pyLslWr8XdIsti
/Wy1r0ntA0u6Pc2alzhiCknOmWmvXMIrbCF4Ql7QJv2A1YOOS2OR8iXSvOWposTBEYocitJmzMls
pV43CQmnM6aW7/sNTWIkPubmi9PrxfsZCFuxlJEifTdK5dLrdmHjTbkkG3f3mnVrHsB9v/vUwEmj
Q4g9KH2AsERMQbsmMLLCDwIz3HwfgvV/e1izq/ni5ur64vUBsAYgqwgwoPygzkTIucWsAeaA/BDV
5ADVn4SmKdH3H8j/X7jSMo4B5DTe8p2cUylp4GhSmzD6nf5D58w2URzlbI5fiOz1gZd0Sv8gsFzz
lZat73Otkq55vn8BYKY/+mpAWnzXgscL3dfV4GpSAxlgHaD6CcUq5mUiqHf6k1xVyfX9SxDOYi7l
9/loHq3TWVYoU1ctigbxQYXQpaiBZTKJRZYGG/7AO3+gONQMJxMcBbUmBtm3EuqJStFQsdsARvGJ
A4pOShGoZnw2qN8oHmjfRLhDBzcZHB/A/wOx2RD/XZCtH6M3RaRPiBpHRXmIYXiI4SKKzwo0Qrt+
NumepmsRZ+zfUVhE2WG6uT8OyWryu+BYE5gbUoVoT2yCQqzxB5he/+dA+cmP6w5Wvr8X/MNRCD7O
5dnsvNsAAZyzshAzUSTN03lP+0byjYdv3vR6f1pV/Gj4+X6tQOPx9x/QtNN0Id09F6o4p5fNUoPR
IczRQ5g/o1QWpWz/bPqst+o0jv8s90I8iozW4ZvlnlDQBemBqzTpEAKatG976lsJ1YiDRwBab3ig
IE0imFpf8SDptX/6w/7TTKizvMuz1aphA0toWMD9P/Qic56UIv514wLS3ewmK2Lqs5LvLCikNy+g
rxKVUubC2cF9IReFigS1z89m9YidZekqWjN6ieIXfvpsXqbsH/jXd5k78UYjD636+euF7tlpgb3A
klGm87K4i+543K3c1FiQ4/iZuhN30CdiIpKs2Dkxbv1qOuxNxkRccyKHYtrTS/i9Y94WSKzQnKhR
cXJTR8B+6upt2w0Ag5VUUziEKMbQzm+lKHbTLG2QigDb7Cp67uToGLZZEU7/pn8gNlPh1C97PX4c
VHhYl8H47O/M0Jc3NzedS1wsZ1d0oeycXV0SP56mWYnbv9Xa4cEmEncioctzJfMuElsnhKr0mmB6
orfFcbZ1VnG03tQADFKeRgnaTovA0JJsWRFWWQFhtdHs1g0vwiAr6jHC1K4Po9UqCspY7aauNre+
V6IgO1IoqjBySuQYOsfGn3G2XO72NClE2FhC7++moVhxsNRASpU5kt8JK49ua/XttrNLYoo0RucI
C3SQlZAON+pYY0DD9pcbZ458QPSxxUbgCl4pyHghmNrgTp4iVBVSkwVkdsWWgkVpEJchrpgQ8CjK
idccbQvLVsTgIU/JV6LNMswUklgyfYlnu6wsLC8WrRjsHK0iLQEmLhCF8c5PKcQNK8+H5E2pwow8
ZV6neMxvmYs9C+JMitBvYdWzU/I6o6DFRmavrewu4uxfFLVYoqPXsTMeo5pBG+cb7ONkQZnBbFYK
225ECrJZzkoJ86C+QEWuoO/p7K19gwpDNCYcqLWEUnv25zpPKj48DRkFE4Mh4SVSdbljlc9TZrOq
nq358PCOIjx0AmTBnn2Zp7kDT28RpHq5fsOiYVHlg7ws3SVZKRkyRJFxAknvgQN4QwnAIqiFoFpC
QHAxC53SWLkC8K5MlrA13Hwqd2mw4PKWIcFv4Viavjm9fvf23U8eAiuSbIsbCTkT7BERa8Q7kt3U
JiOszZalYpECi/SvOsrIZSbGKA5Vhp66Q4BJmGMFecylsAjFslxTTDx7u2KvmNvWjEikJCfq6cqB
suJoHYtdOss0q8otknXJLiUhCcwr1Doy9km6j8VnyJ7KW5RgCfJFJ41eauEjVkz0GCOHOkD0Fsds
8ViCqTUy1ULRxxcpiuhRkq2KLEHoNfnDtJSUqiEeXlSPtUH20yGmHXe1OLduwd+gRH6lyC/NKEry
WBdSrZ6VXKtng8jHZadMbx2KCgounWYIplRRNOg5SSGjdbEnC0N5YIiyWyzGo0OP1uS45CBNJB3t
xl5kqdCYyoqwTDvsZxRvMJqiQiBZzmbv29giJVvCQ9soVBsTTcZtFVfHOvjk64ryAtSQCSSR1Rhr
6WA0izzWH433wEn5Cvglv2f8IU/kaUCvMyzHR7h7tPOahxEScL/LKsGtBtqTZif9cgq93mPD3+dE
fd45ZR4i5uS+EASx4EYdfaI/cq49tGA+DfNmI6hmk05FaRJov4KiizM69kSh3b5BhIf0PjczS6mN
slRi9tN+p84Mynby4jqOVLDZPbHLlAe9OOZr7X1i9F5ScChTYeD8FZeK1cetNg0KMBIYYaSNQVll
u8O2TZMwMqW7Acfqn/Ad9MLpZAqVr8u9owtQo6AiADqPIwB2sgxFHfo491K4iA7gJxgdZEXthcAz
U1EWOlGqF8CJY/TgWKNHDmZpkWliHN29UJTQEhgqRRUtaiolHLUP1D1oNrRIHx0OBURa5h6bGOam
DdKNo65xFS9wOaZdViAxHdFwy0lQTdQ0nizpk4ZZYhsXc6p41VnE9Ev46qzRxrHZQ2/OqpMvrM8d
fRTR18NDSl2ND6j5Jo/oC0VtZHqV7hmRnUbPlApV62cyRZv0oWyUEjPrGcBF6thTpF5iqFm+V8SI
3G63TwmMI5yH5gg5v+eUt2ZA5xbC0954PGYf9BRcRx/yPPaBHh20tW1GhF+I41ZfXKozqdl96eTJ
wKiIQtFM4Iw6L/VkM6f7Et03S318ULYlOFUiKGrPtobqWqpWQD8xamMpEHXB2kvz2JuL04XXf3nc
Hk3u3fbgftDuv3RfhshUk4AvVCEwQEZNT3psDW9JMxqOjnS7K+6VSMkg+rXGGapB40MGOagxREla
15+d84CW2oH8DfVGDMzXFycUd/QVxHyOMZ9zlgGOvc3+mzWPEVS82BPMl/VqVBZxPUCbhiDSrPVF
HBSV17PrZP+8QSyaN2dY9Kusb/j0KjChr8D0YrpajAZhl6s9AlxvoFDYgDufXWip9JwHOBP2e3cA
rL/x2Cc2ojeOLiFnDt0z+71Rb4DH52/ht9XgeCD4KAxHo8HJ8dgd9sb8pNfv8+HyhA+Oh0P3ZNkf
9gR7DkmzDZmFzGYEZzK63xvd1FNpF7gE9FqsYnO5BFXLOxGjVcDRtgwhtrc6Pg6OT07GoxFEDyb9
gRj0lpPjSRhqeXKTZHsTSp1Y8hBpZIyPxSq7FWn0qXIHKDeo6oVYGUPpD3w7rq9N9BKMFnyK8uq7
3rD15ct/AY/4M8w=
===END CRASH DUMP===

**Comment by williamtdr** [comment]
Doh! Will maka a fix for that.
