### ISSUE TITLE
How do i make a .phar

### ISSUE THREAD

**Issue by flaxues** [williamtdr/Steadfast2#4]
I tryed to make a .phar with /makeserver but it's compiling my normal Pocketmine can u make a little tutorial on how to do this?

**Comment by TonyDroidd** [comment]
put the src folder un your PocketMine folder, after, start the server and do /makeserver

or you can donwload the phar here: https://www.dropbox.com/s/z30tg2k82c0x97q/PocketMine-Steadfast_1.5-hybrid.phar?dl=1

**Comment by flaxues** [comment]
Thnx Tony it worked
