### ISSUE TITLE
Players

### ISSUE THREAD

**Issue by flaxues** [williamtdr/Steadfast2#6]
So i saw that i need to change this:

Change the IP to direct players to when the server is full in Player.php - this helps by not turning away players when you can't handle them but instead directing them to another server.

But where do i change it or is it already done?

**Comment by williamtdr** [comment]
Changing that is optional - if you think you can have your server not run against it's limit you don't need to change that. If you want to: https://github.com/williamtdr/Steadfast2/blob/master/src/pocketmine/Player.php#L1497
